In [1]:
import numpy as np

In [2]:
mat0 = np.arange(1, 16).reshape(5,3)
mat0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [3]:
mat1 = np.arange(1, 16).reshape(3,5)
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
results = mat0 @ mat1
results

array([[ 46,  52,  58,  64,  70],
       [100, 115, 130, 145, 160],
       [154, 178, 202, 226, 250],
       [208, 241, 274, 307, 340],
       [262, 304, 346, 388, 430]])